# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2018-01-29 06:38
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0002_auto_20171228_1328'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='views_num',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
